[workspace]
resolver = "2"

members = [ 
    "rs/logd",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }