[package]
name = "logd"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.24", features = ["json", "stream", "multipart", "rustls-tls"], default-features = false }
tokio = { workspace = true }
tokio-stream = { workspace = true }
bytes = "1.5"
inotify = "0.10.2"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }