[package]
edition.workspace = true
name = "logd"
version = "0.1.0"

[dependencies]
bytes = "1.5"
chrono = "0.4.35"
futures = "0.3"
hyper = "1.2"
inotify = "0.10.2"
reqwest = {version = "0.12.5", features = [
    "json",
    "multipart",
    "rustls-tls",
    "stream",
], default-features = false}
rstest = "0.21.0"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0"
tokio = {workspace = true}
tokio-stream = {workspace = true}
tracing = {workspace = true}
tracing-subscriber = {workspace = true}

[dev-dependencies]
dotenv = {workspace = true}
