name: CI

on:
  push:
    branches:
      - main

jobs:
  build-images:
    runs-on: ubuntu-latest

    env:
      IMAGE: "logd"
      REGISTRY: "ghcr.io/hik8s"

    steps:
      - uses: actions/checkout@v2

      - name: Login
        run: echo "${{ secrets.HIK8S_BOT_GHCR_WRITE_TOKEN }}" | docker login ghcr.io -u hik8s --password-stdin
      
      - name: Docker Build
        run: |
          docker build --tag $IMAGE .

      - name: Docker Tag and Push
        run: |
          VERSION=$(grep -E 'version = "[^"]*"$' rs/$IMAGE/Cargo.toml | awk -F\" '{print $2}')
          docker tag $IMAGE $REGISTRY/$IMAGE:$VERSION
          docker push $REGISTRY/$IMAGE:$VERSION
          